version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rezonit_test_task
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: postgres
      DB_HOST: localhost
      DB_NAME: rezonit_test_task
      DB_PASSWORD: secret
      DB_PORT: 5432
      DB_USER: root
      SSL_MODE: disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
