// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type User struct {
	ID        int32  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Age       int32  `json:"age"`
}
